WITH RECURSIVE VIEW AS (
SELECT ID, PARENT_ID, 1 AS LEVEL
FROM ECOLI_DATA
WHERE PARENT_ID IS NULL

UNION ALL

SELECT C.ID, C.PARENT_ID, P.LEVEL + 1 AS LEVEL
FROM VIEW P
JOIN ECOLI_DATA C ON P.ID = C.PARENT_ID
)

SELECT ID
FROM VIEW
WHERE LEVEL = 3
ORDER BY ID asc;