-- 코드를 입력하세요
WITH view_1 AS (
    -- 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능한 자동차 CAR_ID
	SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_CAR
    
    EXCEPT
    
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE >= '2022-11-1'

)
, view AS (
    SELECT v.CAR_ID, c.CAR_TYPE, c.DAILY_FEE, d.DISCOUNT_RATE
    FROM view_1 v
    LEFT JOIN CAR_RENTAL_COMPANY_CAR c
    ON v.CAR_ID = c.CAR_ID
    LEFT JOIN (
        SELECT CAR_TYPE, DISCOUNT_RATE
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
        WHERE DURATION_TYPE = '30일 이상'
    ) d
    ON c.CAR_TYPE = d.CAR_TYPE
    WHERE c.CAR_TYPE IN ('세단','SUV')  -- 자동차 종류가 '세단' 또는 'SUV' 인 자동차    
)

SELECT CAR_ID, CAR_TYPE, ROUND(((DAILY_FEE-(DAILY_FEE*(DISCOUNT_RATE*0.01)))*30),0) AS FEE
FROM view
WHERE ROUND(((DAILY_FEE-(DAILY_FEE*(DISCOUNT_RATE*0.01)))*30),0) >= 500000 
AND ROUND(((DAILY_FEE-(DAILY_FEE*(DISCOUNT_RATE*0.01)))*30),0) < 2000000-- 30일간의 대여 금액이 50만원 이상 200만원 미만
ORDER BY ROUND(((DAILY_FEE-(DAILY_FEE*(DISCOUNT_RATE*0.01)))*30),0) DESC, CAR_TYPE ASC, CAR_ID DESC