WITH view AS (
    -- 대장균 개체 크기에 따라 4등분
    SELECT
    ID,
    NTILE(4) OVER(ORDER BY SIZE_OF_COLONY DESC) AS GRP
    FROM ECOLI_DATA
)

SELECT 
    ID,
    CASE 
    WHEN GRP = 1 THEN 'CRITICAL'
    WHEN GRP = 2 THEN 'HIGH'
    WHEN GRP = 3 THEN 'MEDIUM'
    ELSE 'LOW'
    END AS COLONY_NAME
FROM view
ORDER BY ID ASC
