-- 코드를 작성해주세요
WITH PERCENT AS (
SELECT ID, NTILE(4) OVER(ORDER BY SIZE_OF_COLONY desc) AS RANK_P
FROM ECOLI_DATA
)

SELECT ID, CASE 
WHEN RANK_P = 1 THEN 'CRITICAL'
WHEN RANK_P = 2 THEN 'HIGH'
WHEN RANK_P = 3 THEN 'MEDIUM'
ELSE 'LOW'
END AS COLONY_NAME
FROM PERCENT
ORDER BY ID asc;
