-- 코드를 입력하세요

SELECT V.REST_ID, V.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS,  V.SCORE
FROM (SELECT I.REST_ID, I.REST_NAME, ROUND(AVG(REVIEW_SCORE),2) AS SCORE
      FROM REST_INFO I 
JOIN REST_REVIEW R ON I.REST_ID = R.REST_ID
WHERE I.ADDRESS LIKE '서울%'
GROUP BY I.REST_ID, I.REST_NAME) V
JOIN REST_INFO I ON V.REST_ID = I.REST_ID
ORDER BY V.SCORE desc, I.FAVORITES desc;

