-- 입양기록 O(ANIMAL_OUTS) ,보호소 들어온 기록 X(ANIMAL_INS)인 동물 ID,이름 조회
WITH view AS (
SELECT
    ANIMAL_ID,
    NAME
FROM ANIMAL_OUTS

EXCEPT 

SELECT
    o.ANIMAL_ID,
    o.NAME
FROM ANIMAL_INS i
JOIN ANIMAL_OUTS o
ON o.ANIMAL_ID = i.ANIMAL_ID
)
SELECT *
FROM view
ORDER BY ANIMAL_ID