SELECT 
    CAR_ID,
    CASE 
        WHEN EXISTS (
            SELECT 1 
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY R 
            WHERE R.CAR_ID = C.CAR_ID
              AND '2022-10-16' BETWEEN R.START_DATE AND R.END_DATE
        ) THEN '대여중'
        ELSE '대여 가능'
    END AS AVAILABILITY
FROM (
    SELECT DISTINCT CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) C
ORDER BY CAR_ID DESC;