-- 코드를 입력하세요
WITH VIEW AS(
SELECT D.HISTORY_ID, (DATEDIFF(END_DATE, START_DATE) + 1) AS DURATION,
    T.DAILY_FEE, CASE
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
    ELSE '7일 미만'
    END AS DURATION_TYPE
FROM CAR_RENTAL_COMPANY_CAR T
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY D ON T.CAR_ID = D.CAR_ID
WHERE T.CAR_TYPE = '트럭'
)

SELECT HISTORY_ID, ROUND(V.DAILY_FEE * (1 - (COALESCE(F.DISCOUNT_RATE, 0) / 100)) * V.DURATION, 0) AS FEE
FROM VIEW V
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN F ON V.DURATION_TYPE = F.DURATION_TYPE
AND F.CAR_TYPE = '트럭'
ORDER BY FEE desc, HISTORY_ID desc;