WITH VIEW AS (
    -- 분석 대상 추출(트럭)
    SELECT 
        R.DAILY_FEE,
        H.HISTORY_ID,
        DATEDIFF(H.END_DATE, H.START_DATE)+1 AS DURATION_DATE,
        CASE 
        WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 BETWEEN 7 AND 29 THEN '7일 이상'
        WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 BETWEEN 30 AND 89 THEN '30일 이상'
        WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 >= 90 THEN '90일 이상'
        ELSE '7일 미만'
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_CAR R 
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    ON R.CAR_ID = H.CAR_ID
    WHERE R.CAR_TYPE = '트럭'
)

SELECT 
    V.HISTORY_ID,
    ROUND((V.DAILY_FEE - V.DAILY_FEE * (IFNULL(D.DISCOUNT_RATE,0) * 0.01)) * V.DURATION_DATE, 0) AS FEE 
FROM VIEW V
LEFT JOIN (  -- 7일 미만인 경우도 FEE 계산해야하므로!
    SELECT DURATION_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
) D
ON V.DURATION_TYPE = D.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC
    


