-- 코드를 입력하세요
SELECT C.APNT_NO, PT_NAME, C.PT_NO, C.MCDP_CD, DR_NAME, C.APNT_YMD
FROM PATIENT A, DOCTOR B, APPOINTMENT C
WHERE (B.DR_ID = C.MDDR_ID AND C.PT_NO = A.PT_NO)
AND (TRUNC(C.APNT_YMD,'DD') = TO_DATE('2022-04-13','YYYY-MM-DD') 
AND C.APNT_CNCL_YN = 'N')
AND B.MCDP_CD = 'CS'
ORDER BY C.APNT_YMD asc;