-- 코드를 입력하세요
SELECT 
    C.APNT_NO, 
    P.PT_NAME, 
    C.PT_NO, 
    C.MCDP_CD, 
    D.DR_NAME, 
    C.APNT_YMD
FROM 
    APPOINTMENT C
JOIN DOCTOR D ON C.MDDR_ID = D.DR_ID
JOIN PATIENT P ON C.PT_NO = P.PT_NO
WHERE DATE(C.APNT_YMD) = '2022-04-13'
AND C.APNT_CNCL_YN = 'N'
AND C.MCDP_CD = 'CS'
ORDER BY C.APNT_YMD asc;