-- 코드를 입력하세요
WITH RECURSIVE hours AS (
  SELECT 0 AS HOUR
  UNION ALL
  SELECT HOUR + 1 FROM hours WHERE HOUR < 23
)

SELECT
  H.HOUR,
  COUNT(ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS A
RIGHT JOIN hours H ON HOUR(A.DATETIME) = H.HOUR
GROUP BY H.HOUR
ORDER BY H.HOUR;