-- 코드를 입력하세요
SELECT P.MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW R
JOIN (SELECT MEMBER_PROFILE.MEMBER_ID, MEMBER_NAME, COUNT(REVIEW_ID) AS REVIEW_COUNT
     FROM REST_REVIEW
     JOIN MEMBER_PROFILE ON REST_REVIEW.MEMBER_ID = MEMBER_PROFILE.MEMBER_ID
     GROUP BY MEMBER_PROFILE.MEMBER_ID
     ORDER BY REVIEW_COUNT desc
     LIMIT 1) P
ON R.MEMBER_ID = P.MEMBER_ID
ORDER BY REVIEW_DATE asc, REVIEW_TEXT asc;