-- 1단계: MEMBER_ID별 리뷰 수를 먼저 구함
WITH REVIEW_WITH_COUNT AS (
    SELECT 
        R.MEMBER_ID,
        MP.MEMBER_NAME,
        R.REVIEW_TEXT,
        R.REVIEW_DATE,
        COUNT(*) OVER (PARTITION BY R.MEMBER_ID) AS REVIEW_COUNT
    FROM 
        REST_REVIEW R
    JOIN 
        MEMBER_PROFILE MP ON R.MEMBER_ID = MP.MEMBER_ID
),

-- 2단계: 리뷰 수에 따라 RANK() 적용 (중첩 X)
RANKED_REVIEW AS (
    SELECT *,
        RANK() OVER (ORDER BY REVIEW_COUNT DESC) AS RANKING
    FROM REVIEW_WITH_COUNT
)

-- 최종: 1위 회원의 리뷰만 출력
SELECT 
    MEMBER_NAME, 
    REVIEW_TEXT, 
    DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM 
    RANKED_REVIEW
WHERE 
    RANKING = 1
ORDER BY 
    REVIEW_DATE ASC, REVIEW_TEXT ASC;