-- I: 부모 V: 자식
SELECT V.ITEM_ID, V.ITEM_NAME, V.RARITY
FROM (SELECT ITEM_ID
     FROM ITEM_INFO
     WHERE RARITY = 'RARE') I
JOIN (SELECT T.ITEM_ID, T.PARENT_ITEM_ID, I.ITEM_NAME, I.RARITY
      FROM ITEM_INFO I
      JOIN ITEM_TREE T
      ON I.ITEM_ID = T.ITEM_ID
      WHERE PARENT_ITEM_ID IS NOT NULL
     ) V ON I.ITEM_ID = V.PARENT_ITEM_ID
ORDER BY ITEM_ID desc;