-- 코드를 입력하세요
SELECT MONTH(START_DATE) AS MONTH, C.CAR_ID, COUNT(C.CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
JOIN (SELECT CAR_ID
     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
     WHERE MONTH(START_DATE) BETWEEN '8' AND '10'
     GROUP BY CAR_ID
     HAVING COUNT(START_DATE) >= 5
     ) V
ON C.CAR_ID = V.CAR_ID
WHERE MONTH(START_DATE) BETWEEN '8' AND '10'
GROUP BY MONTH, C.CAR_ID
HAVING COUNT(C.CAR_ID) > 0
ORDER BY MONTH asc, C.CAR_ID desc;