-- 코드를 작성해주세요
WITH VIEW AS(
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, 
    FIRST_VALUE(SIZE_OF_COLONY) OVER(PARTITION BY YEAR(DIFFERENTIATION_DATE) ORDER BY SIZE_OF_COLONY desc) AS LARGEST_SIZE,
    ID
    FROM ECOLI_DATA
)

SELECT V.YEAR, (V.LARGEST_SIZE - E.SIZE_OF_COLONY) AS YEAR_DEV, E.ID
FROM VIEW V
JOIN ECOLI_DATA E 
ON V.YEAR = YEAR(E.DIFFERENTIATION_DATE)
AND V.ID = E.ID
ORDER BY V.YEAR asc, YEAR_DEV asc;