-- 코드를 작성해주세요
SELECT V.ID, I.FISH_NAME, V.LENGTH
FROM (SELECT FISH_TYPE, ID, LENGTH,
      RANK() OVER(PARTITION BY FISH_TYPE ORDER BY LENGTH desc) AS LEVEL
      FROM FISH_INFO) V
JOIN FISH_NAME_INFO I ON V.FISH_TYPE = I.FISH_TYPE
WHERE V.LEVEL = 1
ORDER BY V.ID asc;
